#!/usr/bin/env bash
set -euo pipefail

# Modular, robust start script that works when invoked from project root or from the scripts directory.
# Preserves original behavior by default but adds options and better path handling.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults (matching original behavior)
BUILD_DIR="$PROJECT_ROOT/build"
CMAKE_BUILD_TYPE="Release"
CMAKE_PRESET="conan-release"
CONAN_BUILD_MISSING="--build=missing"

DRY_RUN=0
SKIP_CONAN=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  -b, --build-dir DIR    Build directory (default: $BUILD_DIR)
  -t, --type TYPE        CMake build type (default: $CMAKE_BUILD_TYPE)
      --preset NAME      CMake preset to use (default: $CMAKE_PRESET)
      --no-conan         Skip running 'conan install' and sourcing conanbuild.sh
  -n, --dry-run          Print commands without executing them
  -h, --help             Show this help
EOF
}

# Helper to run commands (respects dry-run)
run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "+ $*"
  else
    echo "+ $*"
    "$@"
  fi
}

# Parse CLI args
while [ $# -gt 0 ]; do
  case "$1" in
    -b|--build-dir)
      BUILD_DIR="$2"
      shift 2
      ;;
    -t|--type)
      CMAKE_BUILD_TYPE="$2"
      shift 2
      ;;
    --preset)
      CMAKE_PRESET="$2"
      shift 2
      ;;
    --no-conan)
      SKIP_CONAN=1
      shift
      ;;
    -n|--dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

echo "Project root: $PROJECT_ROOT"
echo "Build dir: $BUILD_DIR"
echo "Build type: $CMAKE_BUILD_TYPE"
echo "CMake preset: $CMAKE_PRESET"
if [ "$SKIP_CONAN" -eq 1 ]; then
  echo "Conan install: SKIPPED"
else
  echo "Conan install: ENABLED"
fi

# Ensure build dir exists and operate from it for conan install step (keeps behavior)
run mkdir -p "$BUILD_DIR"
run cd "$BUILD_DIR"

if [ "$SKIP_CONAN" -eq 0 ]; then
  # Run conan install pointing at the project root so the command works regardless of where build dir is located
  run conan install "$PROJECT_ROOT" $CONAN_BUILD_MISSING

  # Try to source the generated conanbuild script. Prefer the per-config location (e.g. Release/generators)
  CONAN_SH_PATH="$BUILD_DIR/$CMAKE_BUILD_TYPE/generators/conanbuild.sh"
  if [ -f "$CONAN_SH_PATH" ]; then
    run . "$CONAN_SH_PATH"
  else
    # Fallback: try to find any conanbuild.sh under the build directory
    FOUND="$(ls -1 "$BUILD_DIR"/*/generators/conanbuild.sh 2>/dev/null | head -n1 || true)"
    if [ -n "$FOUND" ] && [ -f "$FOUND" ]; then
      run . "$FOUND"
    else
      echo "Warning: conanbuild.sh not found in expected locations; continuing without sourcing."
    fi
  fi
fi

# Return to project root to run cmake presets (matches original script intent)
run cd "$PROJECT_ROOT"

# Configure using the preset generated by Conan (or present in project)
run cmake --preset "$CMAKE_PRESET"

# Build (match original build invocation)
run cmake --build "$BUILD_DIR/$CMAKE_BUILD_TYPE" --config "$CMAKE_BUILD_TYPE"
